# Generated by Django 5.0.6 on 2024-07-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('idprueba', models.AutoField(db_column='idPrueba', primary_key=True, serialize=False)),
                ('prueba', models.CharField(max_length=20)),
            ],
        ),
    ]
