# Generated by Django 5.0.6 on 2024-07-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0003_prueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prueba',
        ),
    ]
