# Generated by Django 5.0.6 on 2024-07-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cripto', '0004_delete_prueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('run', models.CharField(max_length=12)),
                ('cryptocurrency', models.CharField(max_length=10)),
                ('local_currency_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('crypto_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
